version: '3'

services:
  pagarme-forum:
    container_name: pagarme-forum
    build: .
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis-forum
      - MONGO_HOST=mongo-forum
      - MONGO_DB=forum
    env_file: .env
    volumes:
      - .:/src
    depends_on:
      - mongo-forum
      - redis-forum
    networks:
      - forum-network

  mongo-forum:
    image: mongo
    networks:
      - forum-network

  redis-forum:
    image: redis
    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
